In [179]:
%matplotlib widget
%load_ext autoreload
%autoreload 2


import matplotlib.pyplot as plt
import matplotlib.gridspec as GridSpec
import numpy as np
import os

# from tqdm import tqdm, tqdm_notebook
import math

from  scipy.special import digamma as ψ
from mpmath import besseli as Iν
from scipy.constants import hbar, pi, h, e, k

kB = k
γ = 0.57721566
RQ = h/4/e**2
Φ0 = h/2/e

from JJformulas import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [141]:
Δ = 2.1*kB
R_env = 2e5

SyntaxError: invalid syntax (<ipython-input-142-0872fb3064c7>, line 1)

In [40]:
os.getcwd()

'e:\\OneDrive - Rutgers University\\files_GitHub\\JJ arrays'

In [4]:
EJ_AB(150e3)

0.04517241304820373

In [5]:
Ic (150e3)

1.8950499176670637e-09

In [6]:
data = np.genfromtxt(os.getcwd()+ f'\IcvsEJ.dat')
IcIAB_exp = data[:, 2]
EJ0_exp = data[:, 0]
EJ0_exp

array([8.13031, 0.65602, 0.36831, 0.1087 , 0.04361])

In [173]:
R_list = np.logspace(2, 6, 101)

R_env = 1e5
Tb = 0.05

EJs = EJ_star (EJ = EJ_AB(R_list), R = II(R_env, Rj(R_list, Tb)), T = Tb, C = 1.95e-15)

fig, ax1 = plt.subplots()
ax1.plot( EJ_AB(R_list) , EJs, label = r'C = 1.95 fF')

ax1.plot( EJ_AB(R_list) , EJ_AB(R_list), '--k', alpha = 0.5)
# ax.plot( EJ_AB(R_list) , EJ_AB(R_list)**2 / 5, '--k', alpha = 0.5)

ax1.plot(EJ0_exp, EJ0_exp * IcIAB_exp, 'o' , label = 'exp. data')


ax1.legend()

ax1.set_xscale('log')
ax1.set_yscale('log')

ax1.set_xlabel(r'$E_J, K$')
ax1.set_ylabel(r'$E_J^*, K$')

FigureCanvasNbAgg()

Text(0, 0.5, '$E_J^*, K$')

In [175]:
Rs = [2e3, 10e3, 20e3, 150e3 ]

R_env = 8e4
Tb = 0.05
Cj = 1.5e-15

n = len(Rs)

fig = plt.figure(figsize = (7,10))
gs = GridSpec.GridSpec(n, 1)



Vs = np.linspace(0, 1e-3, 101)


# Rs = [ 200e3 ]

for i, R in enumerate(Rs):
    
    ax = fig.add_subplot(gs[i] )#,sharex=ax)

    Rsh = II(R_env, Rj(R, Tb))
    
    EJ_s = EJ_star (EJ = EJ_AB(R), R = Rsh, T = Tb, C = Cj)
    Is = I_IZ( Vs, EJ = EJ_s, R = Rsh, T = Tb) 


    ax.plot( (Vs - 1*Is*Rsh)/1e-3, (Is)/1e-9, '-', label = 'Rn = {} kOhm, EJ* = {:1.3f} K'.format(R/1e3, EJ_s))

    ax.legend()    
    ax.set_xlabel(r'$V, mV$')
    ax.set_ylabel(r'$I, nA$')

# ax.set_xscale('log')
# ax.set_yscale('log')

plt.tight_layout()

FigureCanvasNbAgg()

In [181]:
R_list = np.logspace(2, 5, 51)

Cj = 1.4e-15
Tb = 0.05

R_env = 2e5

EJs = EJ_star (EJ = EJ_AB(R_list), R = II(R_env, Rj(R_list, Tb)), T = Tb, C = Cj)

fig, ax1 = plt.subplots()

Isw_maxs = []

for R in R_list:
    Isw_max = find_Isw( RN = R, R_env = II(R_env, Rj(R, Tb)), T = Tb, C = Cj)
    Isw_maxs.append(Isw_max)

ax1.plot( EJ_AB(R_list) , np.array(Isw_maxs) / Ic(R_list), label = r'C = {:1.1f} fF'.format(Cj/1e-15))

# ax1.plot( EJ_AB(R_list) , EJ_AB(R_list), '--k', alpha = 0.5)
# ax.plot( EJ_AB(R_list) , EJ_AB(R_list)**2 / 5, '--k', alpha = 0.5)

ax1.plot(EJ0_exp, IcIAB_exp, 'o' , label = 'exp. data')


ax1.legend()

ax1.set_xscale('log')
ax1.set_yscale('log')

ax1.set_xlabel(r'$E_J, K$')
ax1.set_ylabel(r'$I_{sw}/I_{AB}$')

FigureCanvasNbAgg()

Text(0, 0.5, '$I_{sw}/I_{AB}$')

In [15]:
data = np.genfromtxt(os.getcwd()+ f'\R0vsEJ.dat')
R0_exp = data[:, 3]
EJ0_exp = data[:, 2]
EJ0_exp

array([16.26063,  1.31205,  0.73663,  0.2174 ,  0.08722])

In [180]:
R_list = np.logspace(2, 5.5, 51)

R_env = 2e5

Cj = 1.4e-15
Tb = 0.05

EJs = EJ_star (EJ = EJ_AB(R_list), R = R_list, T = Tb, C = Cj)

fig, ax1 = plt.subplots()

R0s = []

for R in R_list:
    R0 = find_R0( RN = R, R_env = II(R_env, Rj(R, Tb)), T = Tb, C = Cj)
    R0s.append(R0)

ax1.plot( EJ_AB(R_list) , R0s, label = r'C = {:1.2f} fF'.format(Cj/1e-15))

# ax1.plot( EJ_AB(R_list) , EJ_AB(R_list), '--k', alpha = 0.5)
# ax.plot( EJ_AB(R_list) , EJ_AB(R_list)**2 / 5, '--k', alpha = 0.5)

ax1.plot(EJ0_exp, R0_exp, 'o' , label = 'exp. data')


ax1.legend()

ax1.set_xscale('log')
ax1.set_yscale('log')

ax1.set_xlabel(r'$E_J, K$')
ax1.set_ylabel(r'$R_0, k \Omega$')

FigureCanvasNbAgg()

Text(0, 0.5, '$R_0, k \\Omega$')

In [139]:
class jj( ):
    def __init__(self, **kwargs ):
        self.vars = ['Ic', 'RN', 'Rj', 'EJ', 'T', 'C', 'EC']
        
        self.Δ = 2.1*kB
        
        for var in self.vars:
            if var not in kwargs.keys():
                kwargs[var] = np.nan
                
            setattr(self,'_' + var, kwargs[var])        
        

        
    def Ic(self):
        if self._Ic is np.nan:
            self._Ic = self.EJ()/ (Φ0/2/pi/kB)
        return self._Ic

    def EJ(self):
        if self._EJ is np.nan:
            self._EJ = self._Ic* (Φ0/2/pi/kB)
        return self._EJ
    
    def RN(self):
        if self._RN is np.nan:
            self._RN = self.Δ / 4 /e /kB /self.EJ()
        return self._RN
    
#     def RN(self):
#         self._RN = self.Δ / 4 /e /kB /self.EJ()
#         return self._RN 

In [140]:
RN_list = np.array([1e3,2e3])
Ic_list = np.array([1e-9,2e-9])


jj(Ic = Ic_list).RN()

array([1.37466311e+20, 6.87331553e+19])