In [3]:
%matplotlib widget
%load_ext autoreload
%autoreload 2


import matplotlib.pyplot as plt
import matplotlib.gridspec as GridSpec
import numpy as np
import os

# from tqdm import tqdm, tqdm_notebook
import math

from  scipy.special import digamma as ψ
from mpmath import besseli as Iν
from scipy.constants import hbar, pi, h, e, k

kB = k
γ = 0.57721566
RQ = h/4/e**2
Φ0 = h/2/e

from JJformulas import *

In [2]:
Δ = 2.1*kB
R_env = 377

SyntaxError: invalid syntax (<ipython-input-142-0872fb3064c7>, line 1)

In [40]:
os.getcwd()

'e:\\OneDrive - Rutgers University\\files_GitHub\\JJ arrays'

In [4]:
EJ_AB(150e3)

0.04517241304820373

In [5]:
Ic (150e3)

1.8950499176670637e-09

# $E_J^* (E_J)$

In [51]:
data = np.genfromtxt(os.getcwd()+ f'\IcvsEJ.dat')
IcIAB_exp = data[:, 2]
EJ0_exp = data[:, 0]
EJ0_exp

array([8.13031, 0.65602, 0.36831, 0.1087 , 0.04361])

In [25]:
R_list = np.logspace(2, 6, 101)

R_env = 377
Tb = 0.05

# EJs = EJ_star (EJ = EJ_AB(R_list), R = II(R_env, Rj(R_list, Tb)), T = Tb, C = 1.95e-15)

EJs = EJ_star_simp (EJ = EJ_AB(R_list),  C = 1.95e-15)

fig, ax1 = plt.subplots()
ax1.plot( EJ_AB(R_list) , EJs, label = r'C = 1.95 fF')

ax1.plot( EJ_AB(R_list) , EJ_AB(R_list), '--k', alpha = 0.5)
# ax.plot( EJ_AB(R_list) , EJ_AB(R_list)**2 / 5, '--k', alpha = 0.5)

ax1.plot(EJ0_exp, EJ0_exp * IcIAB_exp, 'o' , label = 'exp. data')


ax1.legend()

ax1.set_xscale('log')
ax1.set_yscale('log')

ax1.set_xlabel(r'$E_J, K$')
ax1.set_ylabel(r'$E_J^*, K$')

FigureCanvasNbAgg()

Text(0, 0.5, '$E_J^*, K$')

# IVCs

In [52]:
Rs = [1e2, 10e3, 20e3, 150e3 ]

R_env = 2e5
Tb = 0.05
Cj = 1.5e-15

n = len(Rs)

fig = plt.figure(figsize = (7,10))
gs = GridSpec.GridSpec(n, 1)



Vs = np.linspace(0, 1e-2, 101)


# Rs = [ 200e3 ]

for i, R in enumerate(Rs):
    
    ax = fig.add_subplot(gs[i] )#,sharex=ax)

    Rsh = II(R_env, Rj(R, Tb))
    
    EJ_s = EJ_star_simp (EJ = EJ_AB(R),  C = Cj)
#     EJ_s = EJ_star (EJ = EJ_AB(R), R = Rsh, T = Tb, C = Cj)

    Is = I_IZ( Vs, EJ = EJ_s, R = Rsh, T = Tb) 


    ax.plot( (Vs - 1*Is*Rsh)/1e-3, (Is)/1e-9, '-', label = 'Rn = {} kOhm, EJ* = {:1.3f} K'.format(R/1e3, EJ_s))

    ax.legend()    
    ax.set_xlabel(r'$V, mV$')
    ax.set_ylabel(r'$I, nA$')

# ax.set_xscale('log')
# ax.set_yscale('log')

plt.tight_layout()

D:\anaconda\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  if __name__ == '__main__':


FigureCanvasNbAgg()

# $R_0, I_{sw}(E_J)$


In [ ]:
data = np.genfromtxt(os.getcwd()+ f'\IcvsEJ.dat')
IcIAB_exp = data[:, 2]
EJ0_exp = data[:, 0]
EJ0_exp

In [48]:
data = np.genfromtxt(os.getcwd()+ f'\R0vsEJ.dat')
R0_exp = data[:, 3]
EJ0_exp = data[:, 2]
EJ0_exp

array([16.26063,  1.31205,  0.73663,  0.2174 ,  0.08722])

In [82]:
R_list = np.logspace(2, 5, 51)

R_env = 1e5


Cj = 1.5e-15
Tb = 0.05

# EJs = EJ_star_simp (EJ = EJ_AB(R_list), C = Cj)

fig, (ax1, ax2) = plt.subplots(2,1, sharex = True, figsize = (5,5))

R0s = []
Isw_maxs = []

for R in R_list:
    
#     EJs = EJ_star_simp (EJ = EJ_AB(R), C = Cj)
    EJs = EJ_star (EJ= EJ_AB(R), R = II(R_env, Rj(R, Tb)), T = Tb, C = Cj)
    R0, Isw_max = find_R0_Isw( EJ = EJs, R_env = R_env , T = Tb)    
    
    R0s.append(R0)
    Isw_maxs.append(Isw_max)

ax1.plot( EJ_AB(R_list) , R0s, label = r'C = {:1.2f} fF'.format(Cj/1e-15))

# ax1.plot( EJ_AB(R_list) , EJ_AB(R_list), '--k', alpha = 0.5)
# ax.plot( EJ_AB(R_list) , EJ_AB(R_list)**2 / 5, '--k', alpha = 0.5)

ax1.plot(EJ0_exp, R0_exp, 'o' , label = 'exp. data')


ax1.legend()

ax1.set_xscale('log')
ax1.set_yscale('log')

# ax1.set_xlabel(r'$E_J, K$')
ax1.set_ylabel(r'$R_0, k \Omega$')

ax2.plot( EJ_AB(R_list) , np.array(Isw_maxs) / Ic(R_list), label = r'C = {:1.1f} fF'.format(Cj/1e-15))
ax2.plot(EJ0_exp, IcIAB_exp, 'o' , label = 'exp. data')
ax2.legend()

ax2.set_xscale('log')
ax2.set_yscale('log')

ax2.set_xlabel(r'$E_J, K$')
ax2.set_ylabel(r'$I_{sw}/I_{AB}$')

plt.tight_layout()

D:\anaconda\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  # This is added back by InteractiveShellApp.init_path()


FigureCanvasNbAgg()

# $R_0(T)$

In [21]:
RN = 3e3
R_env = 200e3

Cj = 1.4e-15
Tb_list =  np.linspace(0.05, .85, 51)

EJs = EJ_star_simp (EJ = EJ_AB(RN), R = R_env, T = Tb, C = Cj)

fig, ax1 = plt.subplots()

R0s = []

for Tb in Tb_list:
    
    Rsh = II(R_env, Rj(RN, Tb))
    
    R0 = find_R0( RN, R_env = Rsh , T = Tb, C = Cj)
    R0s.append(R0)

ax1.plot( Tb_list , R0s, label = r'C = {:1.2f} fF'.format(Cj/1e-15))




ax1.legend()

# ax1.set_xscale('log')
ax1.set_yscale('log')

ax1.set_xlabel(r'$T, K$')
ax1.set_ylabel(r'$R, k \Omega$')

FigureCanvasNbAgg()

Text(0, 0.5, '$R, k \\Omega$')

# $I_{sw}, R_0 (R_{env})$ 

In [75]:
R_env_list = np.logspace(2, 6, 51)

RN = 7e3

Cj = 1.4e-15
Tb = 0.05


fig, ax1 = plt.subplots()

R0s = []
Isw_maxs = []

for R_env in R_env_list:

    EJs = EJ_star (EJ= EJ_AB(RN), R = R_env, T = Tb, C = Cj)
#     EJs = EJ_star_simp (EJ = EJ_AB(RN), C = Cj)
    
    R0, Isw_max = find_R0_Isw( EJ = EJs, R_env = R_env , T = Tb)
    
    R0s.append(R0)
    Isw_maxs.append(Isw_max)

ax1.plot( R_env_list , R0s, '-', label = r'$R_0$')

ax2 = ax1.twinx()
ax2.plot( R_env_list , np.array(Isw_maxs) / Ic(RN), '--', color = 'C1', label = r'$I_{sw}/I_c$')



ax1.set_xscale('log')
ax1.set_yscale('log')

ax1.set_xlabel(r'$R_{env}, Ohm$')
ax1.set_ylabel(r'$R_0, k \Omega$')

ax2.set_yscale('log')
ax2.set_ylabel(r'$I_{sw}/I_c$')

ax1.legend()
ax2.legend()

plt.tight_layout()

D:\anaconda\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  if __name__ == '__main__':


FigureCanvasNbAgg()

# playing around

In [74]:
EC = 4*e**2/2/1e-15/kB

T = 0.2

E = np.linspace(-3, 3, 101)
f = np.exp (-E**2/ 4 /EC /T )

fig, ax = plt.subplots()

ax.plot(E,f)


D:\anaconda\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  


FigureCanvasNbAgg()

In [44]:
find_R0_Isw( EJ = .01, R_env = 2e1 , T = 0.05)

(994.0098703697229, 1.4322014399176624e-11)

In [139]:
class jj( ):
    def __init__(self, **kwargs ):
        self.vars = ['Ic', 'RN', 'Rj', 'EJ', 'T', 'C', 'EC']
        
        self.Δ = 2.1*kB
        
        for var in self.vars:
            if var not in kwargs.keys():
                kwargs[var] = np.nan
                
            setattr(self,'_' + var, kwargs[var])        
        

        
    def Ic(self):
        if self._Ic is np.nan:
            self._Ic = self.EJ()/ (Φ0/2/pi/kB)
        return self._Ic

    def EJ(self):
        if self._EJ is np.nan:
            self._EJ = self._Ic* (Φ0/2/pi/kB)
        return self._EJ
    
    def RN(self):
        if self._RN is np.nan:
            self._RN = self.Δ / 4 /e /kB /self.EJ()
        return self._RN
    
#     def RN(self):
#         self._RN = self.Δ / 4 /e /kB /self.EJ()
#         return self._RN 

In [140]:
RN_list = np.array([1e3,2e3])
Ic_list = np.array([1e-9,2e-9])


jj(Ic = Ic_list).RN()

array([1.37466311e+20, 6.87331553e+19])